// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	consts "github.com/galaxy-empire-team/bridge-api/pkg/consts"

	mock "github.com/stretchr/testify/mock"

	registry "github.com/galaxy-empire-team/bridge-api/pkg/registry"
)

// RegistryProvider is an autogenerated mock type for the registryProvider type
type RegistryProvider struct {
	mock.Mock
}

type RegistryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *RegistryProvider) EXPECT() *RegistryProvider_Expecter {
	return &RegistryProvider_Expecter{mock: &_m.Mock}
}

// GetFleetUnitStatsByID provides a mock function with given fields: fleetUnitID
func (_m *RegistryProvider) GetFleetUnitStatsByID(fleetUnitID consts.FleetUnitID) (registry.FleetUnitStats, error) {
	ret := _m.Called(fleetUnitID)

	if len(ret) == 0 {
		panic("no return value specified for GetFleetUnitStatsByID")
	}

	var r0 registry.FleetUnitStats
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.FleetUnitID) (registry.FleetUnitStats, error)); ok {
		return rf(fleetUnitID)
	}
	if rf, ok := ret.Get(0).(func(consts.FleetUnitID) registry.FleetUnitStats); ok {
		r0 = rf(fleetUnitID)
	} else {
		r0 = ret.Get(0).(registry.FleetUnitStats)
	}

	if rf, ok := ret.Get(1).(func(consts.FleetUnitID) error); ok {
		r1 = rf(fleetUnitID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetFleetUnitStatsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFleetUnitStatsByID'
type RegistryProvider_GetFleetUnitStatsByID_Call struct {
	*mock.Call
}

// GetFleetUnitStatsByID is a helper method to define mock.On call
//   - fleetUnitID consts.FleetUnitID
func (_e *RegistryProvider_Expecter) GetFleetUnitStatsByID(fleetUnitID interface{}) *RegistryProvider_GetFleetUnitStatsByID_Call {
	return &RegistryProvider_GetFleetUnitStatsByID_Call{Call: _e.mock.On("GetFleetUnitStatsByID", fleetUnitID)}
}

func (_c *RegistryProvider_GetFleetUnitStatsByID_Call) Run(run func(fleetUnitID consts.FleetUnitID)) *RegistryProvider_GetFleetUnitStatsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.FleetUnitID))
	})
	return _c
}

func (_c *RegistryProvider_GetFleetUnitStatsByID_Call) Return(_a0 registry.FleetUnitStats, _a1 error) *RegistryProvider_GetFleetUnitStatsByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetFleetUnitStatsByID_Call) RunAndReturn(run func(consts.FleetUnitID) (registry.FleetUnitStats, error)) *RegistryProvider_GetFleetUnitStatsByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissionIDByType provides a mock function with given fields: missionType
func (_m *RegistryProvider) GetMissionIDByType(missionType consts.MissionType) (consts.MissionID, error) {
	ret := _m.Called(missionType)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionIDByType")
	}

	var r0 consts.MissionID
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.MissionType) (consts.MissionID, error)); ok {
		return rf(missionType)
	}
	if rf, ok := ret.Get(0).(func(consts.MissionType) consts.MissionID); ok {
		r0 = rf(missionType)
	} else {
		r0 = ret.Get(0).(consts.MissionID)
	}

	if rf, ok := ret.Get(1).(func(consts.MissionType) error); ok {
		r1 = rf(missionType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetMissionIDByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissionIDByType'
type RegistryProvider_GetMissionIDByType_Call struct {
	*mock.Call
}

// GetMissionIDByType is a helper method to define mock.On call
//   - missionType consts.MissionType
func (_e *RegistryProvider_Expecter) GetMissionIDByType(missionType interface{}) *RegistryProvider_GetMissionIDByType_Call {
	return &RegistryProvider_GetMissionIDByType_Call{Call: _e.mock.On("GetMissionIDByType", missionType)}
}

func (_c *RegistryProvider_GetMissionIDByType_Call) Run(run func(missionType consts.MissionType)) *RegistryProvider_GetMissionIDByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.MissionType))
	})
	return _c
}

func (_c *RegistryProvider_GetMissionIDByType_Call) Return(_a0 consts.MissionID, _a1 error) *RegistryProvider_GetMissionIDByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetMissionIDByType_Call) RunAndReturn(run func(consts.MissionType) (consts.MissionID, error)) *RegistryProvider_GetMissionIDByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissionTypeByID provides a mock function with given fields: missionID
func (_m *RegistryProvider) GetMissionTypeByID(missionID consts.MissionID) (consts.MissionType, error) {
	ret := _m.Called(missionID)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionTypeByID")
	}

	var r0 consts.MissionType
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.MissionID) (consts.MissionType, error)); ok {
		return rf(missionID)
	}
	if rf, ok := ret.Get(0).(func(consts.MissionID) consts.MissionType); ok {
		r0 = rf(missionID)
	} else {
		r0 = ret.Get(0).(consts.MissionType)
	}

	if rf, ok := ret.Get(1).(func(consts.MissionID) error); ok {
		r1 = rf(missionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetMissionTypeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissionTypeByID'
type RegistryProvider_GetMissionTypeByID_Call struct {
	*mock.Call
}

// GetMissionTypeByID is a helper method to define mock.On call
//   - missionID consts.MissionID
func (_e *RegistryProvider_Expecter) GetMissionTypeByID(missionID interface{}) *RegistryProvider_GetMissionTypeByID_Call {
	return &RegistryProvider_GetMissionTypeByID_Call{Call: _e.mock.On("GetMissionTypeByID", missionID)}
}

func (_c *RegistryProvider_GetMissionTypeByID_Call) Run(run func(missionID consts.MissionID)) *RegistryProvider_GetMissionTypeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.MissionID))
	})
	return _c
}

func (_c *RegistryProvider_GetMissionTypeByID_Call) Return(_a0 consts.MissionType, _a1 error) *RegistryProvider_GetMissionTypeByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetMissionTypeByID_Call) RunAndReturn(run func(consts.MissionID) (consts.MissionType, error)) *RegistryProvider_GetMissionTypeByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNPCStatsByPosition provides a mock function with given fields: positionZ
func (_m *RegistryProvider) GetNPCStatsByPosition(positionZ consts.PlanetPositionZ) (registry.NPCStats, error) {
	ret := _m.Called(positionZ)

	if len(ret) == 0 {
		panic("no return value specified for GetNPCStatsByPosition")
	}

	var r0 registry.NPCStats
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.PlanetPositionZ) (registry.NPCStats, error)); ok {
		return rf(positionZ)
	}
	if rf, ok := ret.Get(0).(func(consts.PlanetPositionZ) registry.NPCStats); ok {
		r0 = rf(positionZ)
	} else {
		r0 = ret.Get(0).(registry.NPCStats)
	}

	if rf, ok := ret.Get(1).(func(consts.PlanetPositionZ) error); ok {
		r1 = rf(positionZ)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetNPCStatsByPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNPCStatsByPosition'
type RegistryProvider_GetNPCStatsByPosition_Call struct {
	*mock.Call
}

// GetNPCStatsByPosition is a helper method to define mock.On call
//   - positionZ consts.PlanetPositionZ
func (_e *RegistryProvider_Expecter) GetNPCStatsByPosition(positionZ interface{}) *RegistryProvider_GetNPCStatsByPosition_Call {
	return &RegistryProvider_GetNPCStatsByPosition_Call{Call: _e.mock.On("GetNPCStatsByPosition", positionZ)}
}

func (_c *RegistryProvider_GetNPCStatsByPosition_Call) Run(run func(positionZ consts.PlanetPositionZ)) *RegistryProvider_GetNPCStatsByPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.PlanetPositionZ))
	})
	return _c
}

func (_c *RegistryProvider_GetNPCStatsByPosition_Call) Return(_a0 registry.NPCStats, _a1 error) *RegistryProvider_GetNPCStatsByPosition_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetNPCStatsByPosition_Call) RunAndReturn(run func(consts.PlanetPositionZ) (registry.NPCStats, error)) *RegistryProvider_GetNPCStatsByPosition_Call {
	_c.Call.Return(run)
	return _c
}

// GetNotificationIDByType provides a mock function with given fields: notificationType
func (_m *RegistryProvider) GetNotificationIDByType(notificationType consts.NotificationType) (consts.NotificationID, error) {
	ret := _m.Called(notificationType)

	if len(ret) == 0 {
		panic("no return value specified for GetNotificationIDByType")
	}

	var r0 consts.NotificationID
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.NotificationType) (consts.NotificationID, error)); ok {
		return rf(notificationType)
	}
	if rf, ok := ret.Get(0).(func(consts.NotificationType) consts.NotificationID); ok {
		r0 = rf(notificationType)
	} else {
		r0 = ret.Get(0).(consts.NotificationID)
	}

	if rf, ok := ret.Get(1).(func(consts.NotificationType) error); ok {
		r1 = rf(notificationType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetNotificationIDByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNotificationIDByType'
type RegistryProvider_GetNotificationIDByType_Call struct {
	*mock.Call
}

// GetNotificationIDByType is a helper method to define mock.On call
//   - notificationType consts.NotificationType
func (_e *RegistryProvider_Expecter) GetNotificationIDByType(notificationType interface{}) *RegistryProvider_GetNotificationIDByType_Call {
	return &RegistryProvider_GetNotificationIDByType_Call{Call: _e.mock.On("GetNotificationIDByType", notificationType)}
}

func (_c *RegistryProvider_GetNotificationIDByType_Call) Run(run func(notificationType consts.NotificationType)) *RegistryProvider_GetNotificationIDByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.NotificationType))
	})
	return _c
}

func (_c *RegistryProvider_GetNotificationIDByType_Call) Return(_a0 consts.NotificationID, _a1 error) *RegistryProvider_GetNotificationIDByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetNotificationIDByType_Call) RunAndReturn(run func(consts.NotificationType) (consts.NotificationID, error)) *RegistryProvider_GetNotificationIDByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetResearchStatsByID provides a mock function with given fields: researchID
func (_m *RegistryProvider) GetResearchStatsByID(researchID consts.ResearchID) (registry.ResearchStats, error) {
	ret := _m.Called(researchID)

	if len(ret) == 0 {
		panic("no return value specified for GetResearchStatsByID")
	}

	var r0 registry.ResearchStats
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.ResearchID) (registry.ResearchStats, error)); ok {
		return rf(researchID)
	}
	if rf, ok := ret.Get(0).(func(consts.ResearchID) registry.ResearchStats); ok {
		r0 = rf(researchID)
	} else {
		r0 = ret.Get(0).(registry.ResearchStats)
	}

	if rf, ok := ret.Get(1).(func(consts.ResearchID) error); ok {
		r1 = rf(researchID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetResearchStatsByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResearchStatsByID'
type RegistryProvider_GetResearchStatsByID_Call struct {
	*mock.Call
}

// GetResearchStatsByID is a helper method to define mock.On call
//   - researchID consts.ResearchID
func (_e *RegistryProvider_Expecter) GetResearchStatsByID(researchID interface{}) *RegistryProvider_GetResearchStatsByID_Call {
	return &RegistryProvider_GetResearchStatsByID_Call{Call: _e.mock.On("GetResearchStatsByID", researchID)}
}

func (_c *RegistryProvider_GetResearchStatsByID_Call) Run(run func(researchID consts.ResearchID)) *RegistryProvider_GetResearchStatsByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.ResearchID))
	})
	return _c
}

func (_c *RegistryProvider_GetResearchStatsByID_Call) Return(_a0 registry.ResearchStats, _a1 error) *RegistryProvider_GetResearchStatsByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetResearchStatsByID_Call) RunAndReturn(run func(consts.ResearchID) (registry.ResearchStats, error)) *RegistryProvider_GetResearchStatsByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetResearchZeroLvlIDByType provides a mock function with given fields: researchType
func (_m *RegistryProvider) GetResearchZeroLvlIDByType(researchType consts.ResearchType) (consts.ResearchID, error) {
	ret := _m.Called(researchType)

	if len(ret) == 0 {
		panic("no return value specified for GetResearchZeroLvlIDByType")
	}

	var r0 consts.ResearchID
	var r1 error
	if rf, ok := ret.Get(0).(func(consts.ResearchType) (consts.ResearchID, error)); ok {
		return rf(researchType)
	}
	if rf, ok := ret.Get(0).(func(consts.ResearchType) consts.ResearchID); ok {
		r0 = rf(researchType)
	} else {
		r0 = ret.Get(0).(consts.ResearchID)
	}

	if rf, ok := ret.Get(1).(func(consts.ResearchType) error); ok {
		r1 = rf(researchType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegistryProvider_GetResearchZeroLvlIDByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResearchZeroLvlIDByType'
type RegistryProvider_GetResearchZeroLvlIDByType_Call struct {
	*mock.Call
}

// GetResearchZeroLvlIDByType is a helper method to define mock.On call
//   - researchType consts.ResearchType
func (_e *RegistryProvider_Expecter) GetResearchZeroLvlIDByType(researchType interface{}) *RegistryProvider_GetResearchZeroLvlIDByType_Call {
	return &RegistryProvider_GetResearchZeroLvlIDByType_Call{Call: _e.mock.On("GetResearchZeroLvlIDByType", researchType)}
}

func (_c *RegistryProvider_GetResearchZeroLvlIDByType_Call) Run(run func(researchType consts.ResearchType)) *RegistryProvider_GetResearchZeroLvlIDByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(consts.ResearchType))
	})
	return _c
}

func (_c *RegistryProvider_GetResearchZeroLvlIDByType_Call) Return(_a0 consts.ResearchID, _a1 error) *RegistryProvider_GetResearchZeroLvlIDByType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *RegistryProvider_GetResearchZeroLvlIDByType_Call) RunAndReturn(run func(consts.ResearchType) (consts.ResearchID, error)) *RegistryProvider_GetResearchZeroLvlIDByType_Call {
	_c.Call.Return(run)
	return _c
}

// NewRegistryProvider creates a new instance of RegistryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRegistryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *RegistryProvider {
	mock := &RegistryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
