// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	consts "github.com/galaxy-empire-team/bridge-api/pkg/consts"

	mock "github.com/stretchr/testify/mock"

	models "github.com/galaxy-empire-team/event-manager/internal/models"

	uuid "github.com/google/uuid"
)

// TxStorages is an autogenerated mock type for the TxStorages type
type TxStorages struct {
	mock.Mock
}

type TxStorages_Expecter struct {
	mock *mock.Mock
}

func (_m *TxStorages) EXPECT() *TxStorages_Expecter {
	return &TxStorages_Expecter{mock: &_m.Mock}
}

// AddFleet provides a mock function with given fields: ctx, planetID, fleet
func (_m *TxStorages) AddFleet(ctx context.Context, planetID uuid.UUID, fleet []models.FleetUnit) error {
	ret := _m.Called(ctx, planetID, fleet)

	if len(ret) == 0 {
		panic("no return value specified for AddFleet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []models.FleetUnit) error); ok {
		r0 = rf(ctx, planetID, fleet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_AddFleet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFleet'
type TxStorages_AddFleet_Call struct {
	*mock.Call
}

// AddFleet is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
//   - fleet []models.FleetUnit
func (_e *TxStorages_Expecter) AddFleet(ctx interface{}, planetID interface{}, fleet interface{}) *TxStorages_AddFleet_Call {
	return &TxStorages_AddFleet_Call{Call: _e.mock.On("AddFleet", ctx, planetID, fleet)}
}

func (_c *TxStorages_AddFleet_Call) Run(run func(ctx context.Context, planetID uuid.UUID, fleet []models.FleetUnit)) *TxStorages_AddFleet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]models.FleetUnit))
	})
	return _c
}

func (_c *TxStorages_AddFleet_Call) Return(_a0 error) *TxStorages_AddFleet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_AddFleet_Call) RunAndReturn(run func(context.Context, uuid.UUID, []models.FleetUnit) error) *TxStorages_AddFleet_Call {
	_c.Call.Return(run)
	return _c
}

// AddResources provides a mock function with given fields: ctx, planetID, resources
func (_m *TxStorages) AddResources(ctx context.Context, planetID uuid.UUID, resources models.Resources) error {
	ret := _m.Called(ctx, planetID, resources)

	if len(ret) == 0 {
		panic("no return value specified for AddResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.Resources) error); ok {
		r0 = rf(ctx, planetID, resources)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_AddResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddResources'
type TxStorages_AddResources_Call struct {
	*mock.Call
}

// AddResources is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
//   - resources models.Resources
func (_e *TxStorages_Expecter) AddResources(ctx interface{}, planetID interface{}, resources interface{}) *TxStorages_AddResources_Call {
	return &TxStorages_AddResources_Call{Call: _e.mock.On("AddResources", ctx, planetID, resources)}
}

func (_c *TxStorages_AddResources_Call) Run(run func(ctx context.Context, planetID uuid.UUID, resources models.Resources)) *TxStorages_AddResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.Resources))
	})
	return _c
}

func (_c *TxStorages_AddResources_Call) Return(_a0 error) *TxStorages_AddResources_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_AddResources_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.Resources) error) *TxStorages_AddResources_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMissionEvent provides a mock function with given fields: ctx, missionEvent
func (_m *TxStorages) CreateMissionEvent(ctx context.Context, missionEvent models.MissionEvent) error {
	ret := _m.Called(ctx, missionEvent)

	if len(ret) == 0 {
		panic("no return value specified for CreateMissionEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.MissionEvent) error); ok {
		r0 = rf(ctx, missionEvent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_CreateMissionEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMissionEvent'
type TxStorages_CreateMissionEvent_Call struct {
	*mock.Call
}

// CreateMissionEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - missionEvent models.MissionEvent
func (_e *TxStorages_Expecter) CreateMissionEvent(ctx interface{}, missionEvent interface{}) *TxStorages_CreateMissionEvent_Call {
	return &TxStorages_CreateMissionEvent_Call{Call: _e.mock.On("CreateMissionEvent", ctx, missionEvent)}
}

func (_c *TxStorages_CreateMissionEvent_Call) Run(run func(ctx context.Context, missionEvent models.MissionEvent)) *TxStorages_CreateMissionEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.MissionEvent))
	})
	return _c
}

func (_c *TxStorages_CreateMissionEvent_Call) Return(_a0 error) *TxStorages_CreateMissionEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_CreateMissionEvent_Call) RunAndReturn(run func(context.Context, models.MissionEvent) error) *TxStorages_CreateMissionEvent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMissionEvents provides a mock function with given fields: ctx, eventsToDelete
func (_m *TxStorages) DeleteMissionEvents(ctx context.Context, eventsToDelete []models.MissionEvent) error {
	ret := _m.Called(ctx, eventsToDelete)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMissionEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.MissionEvent) error); ok {
		r0 = rf(ctx, eventsToDelete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_DeleteMissionEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMissionEvents'
type TxStorages_DeleteMissionEvents_Call struct {
	*mock.Call
}

// DeleteMissionEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - eventsToDelete []models.MissionEvent
func (_e *TxStorages_Expecter) DeleteMissionEvents(ctx interface{}, eventsToDelete interface{}) *TxStorages_DeleteMissionEvents_Call {
	return &TxStorages_DeleteMissionEvents_Call{Call: _e.mock.On("DeleteMissionEvents", ctx, eventsToDelete)}
}

func (_c *TxStorages_DeleteMissionEvents_Call) Run(run func(ctx context.Context, eventsToDelete []models.MissionEvent)) *TxStorages_DeleteMissionEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.MissionEvent))
	})
	return _c
}

func (_c *TxStorages_DeleteMissionEvents_Call) Return(_a0 error) *TxStorages_DeleteMissionEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_DeleteMissionEvents_Call) RunAndReturn(run func(context.Context, []models.MissionEvent) error) *TxStorages_DeleteMissionEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuildings provides a mock function with given fields: ctx, planetID
func (_m *TxStorages) GetBuildings(ctx context.Context, planetID uuid.UUID) ([]consts.BuildingID, error) {
	ret := _m.Called(ctx, planetID)

	if len(ret) == 0 {
		panic("no return value specified for GetBuildings")
	}

	var r0 []consts.BuildingID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]consts.BuildingID, error)); ok {
		return rf(ctx, planetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []consts.BuildingID); ok {
		r0 = rf(ctx, planetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consts.BuildingID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetBuildings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuildings'
type TxStorages_GetBuildings_Call struct {
	*mock.Call
}

// GetBuildings is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
func (_e *TxStorages_Expecter) GetBuildings(ctx interface{}, planetID interface{}) *TxStorages_GetBuildings_Call {
	return &TxStorages_GetBuildings_Call{Call: _e.mock.On("GetBuildings", ctx, planetID)}
}

func (_c *TxStorages_GetBuildings_Call) Run(run func(ctx context.Context, planetID uuid.UUID)) *TxStorages_GetBuildings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetBuildings_Call) Return(_a0 []consts.BuildingID, _a1 error) *TxStorages_GetBuildings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetBuildings_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]consts.BuildingID, error)) *TxStorages_GetBuildings_Call {
	_c.Call.Return(run)
	return _c
}

// GetMissionEvents provides a mock function with given fields: ctx, missionEventsCount
func (_m *TxStorages) GetMissionEvents(ctx context.Context, missionEventsCount uint16) ([]models.MissionEvent, error) {
	ret := _m.Called(ctx, missionEventsCount)

	if len(ret) == 0 {
		panic("no return value specified for GetMissionEvents")
	}

	var r0 []models.MissionEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint16) ([]models.MissionEvent, error)); ok {
		return rf(ctx, missionEventsCount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint16) []models.MissionEvent); ok {
		r0 = rf(ctx, missionEventsCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MissionEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint16) error); ok {
		r1 = rf(ctx, missionEventsCount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetMissionEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMissionEvents'
type TxStorages_GetMissionEvents_Call struct {
	*mock.Call
}

// GetMissionEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - missionEventsCount uint16
func (_e *TxStorages_Expecter) GetMissionEvents(ctx interface{}, missionEventsCount interface{}) *TxStorages_GetMissionEvents_Call {
	return &TxStorages_GetMissionEvents_Call{Call: _e.mock.On("GetMissionEvents", ctx, missionEventsCount)}
}

func (_c *TxStorages_GetMissionEvents_Call) Run(run func(ctx context.Context, missionEventsCount uint16)) *TxStorages_GetMissionEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint16))
	})
	return _c
}

func (_c *TxStorages_GetMissionEvents_Call) Return(_a0 []models.MissionEvent, _a1 error) *TxStorages_GetMissionEvents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetMissionEvents_Call) RunAndReturn(run func(context.Context, uint16) ([]models.MissionEvent, error)) *TxStorages_GetMissionEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlanetFleetForUpdate provides a mock function with given fields: ctx, planetID
func (_m *TxStorages) GetPlanetFleetForUpdate(ctx context.Context, planetID uuid.UUID) ([]models.FleetUnit, error) {
	ret := _m.Called(ctx, planetID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanetFleetForUpdate")
	}

	var r0 []models.FleetUnit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.FleetUnit, error)); ok {
		return rf(ctx, planetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.FleetUnit); ok {
		r0 = rf(ctx, planetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.FleetUnit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetPlanetFleetForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlanetFleetForUpdate'
type TxStorages_GetPlanetFleetForUpdate_Call struct {
	*mock.Call
}

// GetPlanetFleetForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
func (_e *TxStorages_Expecter) GetPlanetFleetForUpdate(ctx interface{}, planetID interface{}) *TxStorages_GetPlanetFleetForUpdate_Call {
	return &TxStorages_GetPlanetFleetForUpdate_Call{Call: _e.mock.On("GetPlanetFleetForUpdate", ctx, planetID)}
}

func (_c *TxStorages_GetPlanetFleetForUpdate_Call) Run(run func(ctx context.Context, planetID uuid.UUID)) *TxStorages_GetPlanetFleetForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetPlanetFleetForUpdate_Call) Return(_a0 []models.FleetUnit, _a1 error) *TxStorages_GetPlanetFleetForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetPlanetFleetForUpdate_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.FleetUnit, error)) *TxStorages_GetPlanetFleetForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlanetInfoByCoordinates provides a mock function with given fields: ctx, planetFrom
func (_m *TxStorages) GetPlanetInfoByCoordinates(ctx context.Context, planetFrom models.Coordinates) (models.Planet, error) {
	ret := _m.Called(ctx, planetFrom)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanetInfoByCoordinates")
	}

	var r0 models.Planet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Coordinates) (models.Planet, error)); ok {
		return rf(ctx, planetFrom)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Coordinates) models.Planet); ok {
		r0 = rf(ctx, planetFrom)
	} else {
		r0 = ret.Get(0).(models.Planet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Coordinates) error); ok {
		r1 = rf(ctx, planetFrom)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetPlanetInfoByCoordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlanetInfoByCoordinates'
type TxStorages_GetPlanetInfoByCoordinates_Call struct {
	*mock.Call
}

// GetPlanetInfoByCoordinates is a helper method to define mock.On call
//   - ctx context.Context
//   - planetFrom models.Coordinates
func (_e *TxStorages_Expecter) GetPlanetInfoByCoordinates(ctx interface{}, planetFrom interface{}) *TxStorages_GetPlanetInfoByCoordinates_Call {
	return &TxStorages_GetPlanetInfoByCoordinates_Call{Call: _e.mock.On("GetPlanetInfoByCoordinates", ctx, planetFrom)}
}

func (_c *TxStorages_GetPlanetInfoByCoordinates_Call) Run(run func(ctx context.Context, planetFrom models.Coordinates)) *TxStorages_GetPlanetInfoByCoordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Coordinates))
	})
	return _c
}

func (_c *TxStorages_GetPlanetInfoByCoordinates_Call) Return(_a0 models.Planet, _a1 error) *TxStorages_GetPlanetInfoByCoordinates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetPlanetInfoByCoordinates_Call) RunAndReturn(run func(context.Context, models.Coordinates) (models.Planet, error)) *TxStorages_GetPlanetInfoByCoordinates_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlanetInfoByID provides a mock function with given fields: ctx, planetID
func (_m *TxStorages) GetPlanetInfoByID(ctx context.Context, planetID uuid.UUID) (models.Planet, error) {
	ret := _m.Called(ctx, planetID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanetInfoByID")
	}

	var r0 models.Planet
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Planet, error)); ok {
		return rf(ctx, planetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Planet); ok {
		r0 = rf(ctx, planetID)
	} else {
		r0 = ret.Get(0).(models.Planet)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetPlanetInfoByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlanetInfoByID'
type TxStorages_GetPlanetInfoByID_Call struct {
	*mock.Call
}

// GetPlanetInfoByID is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
func (_e *TxStorages_Expecter) GetPlanetInfoByID(ctx interface{}, planetID interface{}) *TxStorages_GetPlanetInfoByID_Call {
	return &TxStorages_GetPlanetInfoByID_Call{Call: _e.mock.On("GetPlanetInfoByID", ctx, planetID)}
}

func (_c *TxStorages_GetPlanetInfoByID_Call) Run(run func(ctx context.Context, planetID uuid.UUID)) *TxStorages_GetPlanetInfoByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetPlanetInfoByID_Call) Return(_a0 models.Planet, _a1 error) *TxStorages_GetPlanetInfoByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetPlanetInfoByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Planet, error)) *TxStorages_GetPlanetInfoByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlanetMinesProduction provides a mock function with given fields: ctx, planetID
func (_m *TxStorages) GetPlanetMinesProduction(ctx context.Context, planetID uuid.UUID) (map[consts.BuildingType]uint64, error) {
	ret := _m.Called(ctx, planetID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlanetMinesProduction")
	}

	var r0 map[consts.BuildingType]uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (map[consts.BuildingType]uint64, error)); ok {
		return rf(ctx, planetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) map[consts.BuildingType]uint64); ok {
		r0 = rf(ctx, planetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[consts.BuildingType]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetPlanetMinesProduction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlanetMinesProduction'
type TxStorages_GetPlanetMinesProduction_Call struct {
	*mock.Call
}

// GetPlanetMinesProduction is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
func (_e *TxStorages_Expecter) GetPlanetMinesProduction(ctx interface{}, planetID interface{}) *TxStorages_GetPlanetMinesProduction_Call {
	return &TxStorages_GetPlanetMinesProduction_Call{Call: _e.mock.On("GetPlanetMinesProduction", ctx, planetID)}
}

func (_c *TxStorages_GetPlanetMinesProduction_Call) Run(run func(ctx context.Context, planetID uuid.UUID)) *TxStorages_GetPlanetMinesProduction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetPlanetMinesProduction_Call) Return(_a0 map[consts.BuildingType]uint64, _a1 error) *TxStorages_GetPlanetMinesProduction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetPlanetMinesProduction_Call) RunAndReturn(run func(context.Context, uuid.UUID) (map[consts.BuildingType]uint64, error)) *TxStorages_GetPlanetMinesProduction_Call {
	_c.Call.Return(run)
	return _c
}

// GetResources provides a mock function with given fields: ctx, planetID
func (_m *TxStorages) GetResources(ctx context.Context, planetID uuid.UUID) (models.Resources, error) {
	ret := _m.Called(ctx, planetID)

	if len(ret) == 0 {
		panic("no return value specified for GetResources")
	}

	var r0 models.Resources
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Resources, error)); ok {
		return rf(ctx, planetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Resources); ok {
		r0 = rf(ctx, planetID)
	} else {
		r0 = ret.Get(0).(models.Resources)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResources'
type TxStorages_GetResources_Call struct {
	*mock.Call
}

// GetResources is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
func (_e *TxStorages_Expecter) GetResources(ctx interface{}, planetID interface{}) *TxStorages_GetResources_Call {
	return &TxStorages_GetResources_Call{Call: _e.mock.On("GetResources", ctx, planetID)}
}

func (_c *TxStorages_GetResources_Call) Run(run func(ctx context.Context, planetID uuid.UUID)) *TxStorages_GetResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetResources_Call) Return(_a0 models.Resources, _a1 error) *TxStorages_GetResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetResources_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Resources, error)) *TxStorages_GetResources_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourcesForUpdate provides a mock function with given fields: ctx, planetID
func (_m *TxStorages) GetResourcesForUpdate(ctx context.Context, planetID uuid.UUID) (models.Resources, error) {
	ret := _m.Called(ctx, planetID)

	if len(ret) == 0 {
		panic("no return value specified for GetResourcesForUpdate")
	}

	var r0 models.Resources
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.Resources, error)); ok {
		return rf(ctx, planetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.Resources); ok {
		r0 = rf(ctx, planetID)
	} else {
		r0 = ret.Get(0).(models.Resources)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, planetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetResourcesForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourcesForUpdate'
type TxStorages_GetResourcesForUpdate_Call struct {
	*mock.Call
}

// GetResourcesForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
func (_e *TxStorages_Expecter) GetResourcesForUpdate(ctx interface{}, planetID interface{}) *TxStorages_GetResourcesForUpdate_Call {
	return &TxStorages_GetResourcesForUpdate_Call{Call: _e.mock.On("GetResourcesForUpdate", ctx, planetID)}
}

func (_c *TxStorages_GetResourcesForUpdate_Call) Run(run func(ctx context.Context, planetID uuid.UUID)) *TxStorages_GetResourcesForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetResourcesForUpdate_Call) Return(_a0 models.Resources, _a1 error) *TxStorages_GetResourcesForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetResourcesForUpdate_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.Resources, error)) *TxStorages_GetResourcesForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserResearches provides a mock function with given fields: ctx, userID
func (_m *TxStorages) GetUserResearches(ctx context.Context, userID uuid.UUID) ([]consts.ResearchID, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserResearches")
	}

	var r0 []consts.ResearchID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]consts.ResearchID, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []consts.ResearchID); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]consts.ResearchID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetUserResearches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserResearches'
type TxStorages_GetUserResearches_Call struct {
	*mock.Call
}

// GetUserResearches is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *TxStorages_Expecter) GetUserResearches(ctx interface{}, userID interface{}) *TxStorages_GetUserResearches_Call {
	return &TxStorages_GetUserResearches_Call{Call: _e.mock.On("GetUserResearches", ctx, userID)}
}

func (_c *TxStorages_GetUserResearches_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *TxStorages_GetUserResearches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *TxStorages_GetUserResearches_Call) Return(_a0 []consts.ResearchID, _a1 error) *TxStorages_GetUserResearches_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetUserResearches_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]consts.ResearchID, error)) *TxStorages_GetUserResearches_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserResearchesByTypes provides a mock function with given fields: ctx, userID, researchTypes
func (_m *TxStorages) GetUserResearchesByTypes(ctx context.Context, userID uuid.UUID, researchTypes []consts.ResearchType) (map[consts.ResearchType]consts.ResearchID, error) {
	ret := _m.Called(ctx, userID, researchTypes)

	if len(ret) == 0 {
		panic("no return value specified for GetUserResearchesByTypes")
	}

	var r0 map[consts.ResearchType]consts.ResearchID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []consts.ResearchType) (map[consts.ResearchType]consts.ResearchID, error)); ok {
		return rf(ctx, userID, researchTypes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []consts.ResearchType) map[consts.ResearchType]consts.ResearchID); ok {
		r0 = rf(ctx, userID, researchTypes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[consts.ResearchType]consts.ResearchID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, []consts.ResearchType) error); ok {
		r1 = rf(ctx, userID, researchTypes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TxStorages_GetUserResearchesByTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserResearchesByTypes'
type TxStorages_GetUserResearchesByTypes_Call struct {
	*mock.Call
}

// GetUserResearchesByTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - researchTypes []consts.ResearchType
func (_e *TxStorages_Expecter) GetUserResearchesByTypes(ctx interface{}, userID interface{}, researchTypes interface{}) *TxStorages_GetUserResearchesByTypes_Call {
	return &TxStorages_GetUserResearchesByTypes_Call{Call: _e.mock.On("GetUserResearchesByTypes", ctx, userID, researchTypes)}
}

func (_c *TxStorages_GetUserResearchesByTypes_Call) Run(run func(ctx context.Context, userID uuid.UUID, researchTypes []consts.ResearchType)) *TxStorages_GetUserResearchesByTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]consts.ResearchType))
	})
	return _c
}

func (_c *TxStorages_GetUserResearchesByTypes_Call) Return(_a0 map[consts.ResearchType]consts.ResearchID, _a1 error) *TxStorages_GetUserResearchesByTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TxStorages_GetUserResearchesByTypes_Call) RunAndReturn(run func(context.Context, uuid.UUID, []consts.ResearchType) (map[consts.ResearchType]consts.ResearchID, error)) *TxStorages_GetUserResearchesByTypes_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNotificationEvents provides a mock function with given fields: ctx, notificationEvents
func (_m *TxStorages) SaveNotificationEvents(ctx context.Context, notificationEvents []models.NotificationEvent) error {
	ret := _m.Called(ctx, notificationEvents)

	if len(ret) == 0 {
		panic("no return value specified for SaveNotificationEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.NotificationEvent) error); ok {
		r0 = rf(ctx, notificationEvents)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_SaveNotificationEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNotificationEvents'
type TxStorages_SaveNotificationEvents_Call struct {
	*mock.Call
}

// SaveNotificationEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationEvents []models.NotificationEvent
func (_e *TxStorages_Expecter) SaveNotificationEvents(ctx interface{}, notificationEvents interface{}) *TxStorages_SaveNotificationEvents_Call {
	return &TxStorages_SaveNotificationEvents_Call{Call: _e.mock.On("SaveNotificationEvents", ctx, notificationEvents)}
}

func (_c *TxStorages_SaveNotificationEvents_Call) Run(run func(ctx context.Context, notificationEvents []models.NotificationEvent)) *TxStorages_SaveNotificationEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.NotificationEvent))
	})
	return _c
}

func (_c *TxStorages_SaveNotificationEvents_Call) Return(_a0 error) *TxStorages_SaveNotificationEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_SaveNotificationEvents_Call) RunAndReturn(run func(context.Context, []models.NotificationEvent) error) *TxStorages_SaveNotificationEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SetPlanetFleet provides a mock function with given fields: ctx, planetID, fleet
func (_m *TxStorages) SetPlanetFleet(ctx context.Context, planetID uuid.UUID, fleet []models.FleetUnit) error {
	ret := _m.Called(ctx, planetID, fleet)

	if len(ret) == 0 {
		panic("no return value specified for SetPlanetFleet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []models.FleetUnit) error); ok {
		r0 = rf(ctx, planetID, fleet)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_SetPlanetFleet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPlanetFleet'
type TxStorages_SetPlanetFleet_Call struct {
	*mock.Call
}

// SetPlanetFleet is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
//   - fleet []models.FleetUnit
func (_e *TxStorages_Expecter) SetPlanetFleet(ctx interface{}, planetID interface{}, fleet interface{}) *TxStorages_SetPlanetFleet_Call {
	return &TxStorages_SetPlanetFleet_Call{Call: _e.mock.On("SetPlanetFleet", ctx, planetID, fleet)}
}

func (_c *TxStorages_SetPlanetFleet_Call) Run(run func(ctx context.Context, planetID uuid.UUID, fleet []models.FleetUnit)) *TxStorages_SetPlanetFleet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]models.FleetUnit))
	})
	return _c
}

func (_c *TxStorages_SetPlanetFleet_Call) Return(_a0 error) *TxStorages_SetPlanetFleet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_SetPlanetFleet_Call) RunAndReturn(run func(context.Context, uuid.UUID, []models.FleetUnit) error) *TxStorages_SetPlanetFleet_Call {
	_c.Call.Return(run)
	return _c
}

// SetResources provides a mock function with given fields: ctx, planetID, updatedResources
func (_m *TxStorages) SetResources(ctx context.Context, planetID uuid.UUID, updatedResources models.Resources) error {
	ret := _m.Called(ctx, planetID, updatedResources)

	if len(ret) == 0 {
		panic("no return value specified for SetResources")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.Resources) error); ok {
		r0 = rf(ctx, planetID, updatedResources)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TxStorages_SetResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetResources'
type TxStorages_SetResources_Call struct {
	*mock.Call
}

// SetResources is a helper method to define mock.On call
//   - ctx context.Context
//   - planetID uuid.UUID
//   - updatedResources models.Resources
func (_e *TxStorages_Expecter) SetResources(ctx interface{}, planetID interface{}, updatedResources interface{}) *TxStorages_SetResources_Call {
	return &TxStorages_SetResources_Call{Call: _e.mock.On("SetResources", ctx, planetID, updatedResources)}
}

func (_c *TxStorages_SetResources_Call) Run(run func(ctx context.Context, planetID uuid.UUID, updatedResources models.Resources)) *TxStorages_SetResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.Resources))
	})
	return _c
}

func (_c *TxStorages_SetResources_Call) Return(_a0 error) *TxStorages_SetResources_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TxStorages_SetResources_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.Resources) error) *TxStorages_SetResources_Call {
	_c.Call.Return(run)
	return _c
}

// NewTxStorages creates a new instance of TxStorages. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTxStorages(t interface {
	mock.TestingT
	Cleanup(func())
}) *TxStorages {
	mock := &TxStorages{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
